# Site settings
title: Matthias Lischka
description: '<p>Passionate software developer<br />agile fanatic<br />test addict<br />open source enthusiast</p><p>Professional nerd</p><p>Sports, mountains and travel when AFK</p>'
url: 'https://matthiaslischka.at'
baseurl: ''

google_analytics: 'UA-37678138-1'
disqus_shortname: 'matthiaslischka'

remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'Matthias Lischka'
  email: mail@matthiaslischka.at
  twitter_username: matthiaslischka
  #facebook_username: joshgerdes
  github_username:  matthiaslischka
  linkedin_username:  matthias-lischka-9322a3175
  
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']